spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache : false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true